### PR TITLE
Check for components when using FindPoco

### LINKED ISSUE #37: cmake accepts versions of poco which are too old
I have poco 1.4.6 installed.  cmake is selecting my system poco, but I do not have the JSON component, and build fails.

### PR DESCRIPTION
**Pull request by xloem**
Fixes #37 for me

### CODE REVIEW

**Comment by xloem** [comment]
Breaks systems where FindPoco returns true; variables I check do not exist

**Comment by guruofquality** [comment]
Any more changes? It looks sensible to merge

**Comment by xloem** [comment]
That's it.  But I made a separate branch which checks the version as you mentioned.

**Comment by guruofquality** [comment]
Aha, so here is why AppVeyor is failing:

In the installed PocoConfig.cmake case ```Find Poco with PocoConfig.cmake (installed copy)```, Poco_VERSION is actually set, however its not a hex number, its an actual version string 1.6.0 for example. And to top it off, Poco_INCLUDE_DIRS is not set because its that new style imported library target where the includes are embedded with the library target. This last one actually causes the failure.

So the work around to make everything happy here would be to make the version check only within the SetupPoco.cmake inside the ```Find Poco with FindPoco.cmake (local copy)``` section. We don't need a version check for the PocoConfig.cmake because that only exists for 1.6 and up. Sorry for the tedious mess.

**Comment by guruofquality** [comment]
@xloem thanks a lot, and sorry for the tedium

**Pull request merged**
